[build]
  publish = "."
  command = "echo 'No build required for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    SUPABASE_URL = "https://vumyufckkdeeszxvmyjb.supabase.co"

[context.deploy-preview]
  [context.deploy-preview.environment]
    SUPABASE_URL = "https://vumyufckkdeeszxvmyjb.supabase.co"
